// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amayklqjcnwejshnzwlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtYXlrbHFqY253ZWpzaG56d2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjgyODUsImV4cCI6MjA2MDY0NDI4NX0.du-EitmZ4DSqriBotteUYoeOFsKPnHhIvC0yAtn03g4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);